### ISSUE TITLE
Leerer Owner

### ISSUE THREAD

**Issue by misto** [IFS-Web/HSR.WED3.Server#1]
Ich bin als user1 eingeloggt und frage /accounts ab, dann erhalte ich einen leeren owner:

```
{"ownerId":"AUrAaWxRqklqvDhN","accountNr":"1000001","amount":1033,"owner":{}}
```

**Comment by sgeh** [comment]
Fixed in latest commit, see [c78903a](https://github.com/IFS-Web/HSR.WED3.Server/commit/c78903acbee4791faa07d9d9cc1f2db4cc11ffff)

**Comment by misto** [comment]
Yup, works. Thanks!
